spring:
  profiles:
    active: "dev"
  thymeleaf:
    cache: false
    encoding: UTF-8
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
    multipart:
      max-file-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: cafe.crm.test@gmail.com
    password: Integer123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      defaultEncoding: UTF-8
#Logging
logging:
  config: classpath:logback.xml

time:
 server: ntp.xs4all.nl,ntp04.oal.ul.pt,ntp02.oal.ul.pt,time-a.nist.gov

defaultUser:
  roles: BOSS,MANAGER

advertising:
  mail:
    sender: smtp.gmail.com
    image-view: db:image-advertising
    text-view: db:text-advertising
    disable-view: db:disable-advertising
    disable-subject: Отключение рекламной рассылки
  cloud:
    name: hookahpacman
    key: 172681431197699
    secret: p1B4kuIACB-7avW2KXrAXgHuMj0

site:
  address: localhost:8080

user:
  default-password: hookahpacman

balance-info:
  mail:
    deduction:
      view: db:balance-info-deduction
      subject: Изменение баланса карты!
    refill:
      view: db:balance-info-refill
      subject: Измение баланса карты!

closeShiftEmailShortage:
           view: db:closeShiftEmailShortage
           text: Касса не сошлась!
           subject: Касса не сошлась!

vk:
  application-id:  # application id in vk
  application-secret:  # application secret key
  message-name: daily-report # name of template in db
  chat-id:  # id of conference
  access-token:
  api-version: 5.68 # vk api version
  mail: # Notification to email
    invalid-token:
      view: db:invalid-token
      subject: Токен доступа недействителен

card:
 enable: false  # Включить, отключить рекламу (true false)

reCaptcha:
  apiUrl: https://www.google.com/recaptcha/api/siteverify
  secretKey: 6LcmCzMUAAAAAAnMaxexPbqr8oNzYzke-gcPTYFz



property:
  name:
    masterKey: masterKey
    price:
      firstHour: Цена за первый час
      nextHours: Цена за последующие часы
      refBonus: Реферальный бонус
    vk: vk

mail:
  default-smtp: smtp.gmail.com